name: "Setup and install"
description: "Common setup steps for Actions"

inputs:
  # https://vercel.com/docs/functions/runtimes/node-js/node-js-versions
  node-version:
    description: "Node.js version"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
