"""create t_posts

Revision ID: eafe7933236d
Revises: ddbc26ca419e
Create Date: 2025-09-23 11:15:34.134878+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eafe7933236d"
down_revision: str | Sequence[str] | None = "ddbc26ca419e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_posts",
        sa.Column("post_id", sa.SMALLINT(), nullable=False),
        sa.Column("user_id", sa.SMALLINT(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=200), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id"),
        comment="投稿",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_posts")
    # ### end Alembic commands ###
