"""create t_users

Revision ID: ddbc26ca419e
Revises:
Create Date: 2025-09-23 11:07:35.000665+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddbc26ca419e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_users",
        sa.Column("user_id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("username", sa.VARCHAR(length=200), nullable=True),
        sa.Column("email", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_street", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_suite", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_city", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_zipcode", sa.VARCHAR(length=200), nullable=True),
        sa.Column("geo_lat", sa.REAL(), nullable=True),
        sa.Column("geo_lng", sa.REAL(), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=200), nullable=True),
        sa.Column("website", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_catch_phrase", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_bs", sa.VARCHAR(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        comment="ユーザー",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_users")
    # ### end Alembic commands ###
