"""create table

Revision ID: 9d1b9f166528
Revises:
Create Date: 2025-10-02 19:14:19.111635+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d1b9f166528"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_comments",
        sa.Column("comment_id", sa.SMALLINT(), nullable=False),
        sa.Column("post_id", sa.SMALLINT(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("email", sa.VARCHAR(length=200), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
        comment="コメント",
    )
    op.create_table(
        "t_posts",
        sa.Column("post_id", sa.SMALLINT(), nullable=False),
        sa.Column("user_id", sa.SMALLINT(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=200), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id"),
        comment="投稿",
    )
    op.create_table(
        "t_todos",
        sa.Column("todo_id", sa.SMALLINT(), nullable=False),
        sa.Column("user_id", sa.SMALLINT(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=200), nullable=True),
        sa.Column("completed", sa.SMALLINT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("todo_id"),
        comment="ToDo",
    )
    op.create_table(
        "t_users",
        sa.Column("user_id", sa.SMALLINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("username", sa.VARCHAR(length=200), nullable=True),
        sa.Column("email", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_street", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_suite", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_city", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address_zipcode", sa.VARCHAR(length=200), nullable=True),
        sa.Column("geo_lat", sa.REAL(), nullable=True),
        sa.Column("geo_lng", sa.REAL(), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=200), nullable=True),
        sa.Column("website", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_catch_phrase", sa.VARCHAR(length=200), nullable=True),
        sa.Column("company_bs", sa.VARCHAR(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        comment="ユーザー",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_users")
    op.drop_table("t_todos")
    op.drop_table("t_posts")
    op.drop_table("t_comments")
    # ### end Alembic commands ###
