"""create t_comments

Revision ID: b4d7f3ca0b3d
Revises: c1012eca6ace
Create Date: 2025-09-23 11:24:51.145517+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4d7f3ca0b3d"
down_revision: str | Sequence[str] | None = "c1012eca6ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_comments",
        sa.Column("comment_id", sa.SMALLINT(), nullable=False),
        sa.Column("post_id", sa.SMALLINT(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("email", sa.VARCHAR(length=200), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
        comment="コメント",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_comments")
    # ### end Alembic commands ###
