"""create t_todos

Revision ID: c1012eca6ace
Revises: eafe7933236d
Create Date: 2025-09-23 11:20:13.855835+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1012eca6ace"
down_revision: str | Sequence[str] | None = "eafe7933236d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_todos",
        sa.Column("todo_id", sa.SMALLINT(), nullable=False),
        sa.Column("user_id", sa.SMALLINT(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=200), nullable=True),
        sa.Column("completed", sa.SMALLINT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("todo_id"),
        comment="ToDo",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("t_todos")
    # ### end Alembic commands ###
