name: Check

on:
  push:
    branches-ignore:
      - main
    paths:
      - "config/**"
      - "src/**"
      - ".github/workflows/*.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Format
        run: uv run ruff format .

      - name: Lint
        run: uv run ruff check --fix .

      - name: Typecheck
        run: uv run ty check
